version: "3.9"
services:
  app-authn-authz:
    build:
      context: .
      dockerfile: Dockerfile
      # network: host
    # network_mode: host
    command: ./startup-script.sh
    networks:
      - skillup-network
    # networks:
    #   hostnet: {}
    # extra_hosts:
    #   - "host.docker.internal:host-gateway"
    volumes:
      - $PWD/server:/AUTHN-AUTHZ-SERVER/server
    ports:
      - 7777:70 # express and exposed docker port are the same
      - 9230:9229 # this is the debug port
    restart: unless-stopped

volumes:
  server:

networks:
  skillup-network:
    external: true

# networks:
#   hostnet:
#     external: true
#     name: host

# networks:
#   default:
#     external: true
#     name: skillup-network
