version: "3.9"
services:
  app-authn-authz:
    build:
      context: .
      dockerfile: Dockerfile
    command: ./startup-script.sh
    volumes:
      - $PWD/server:/AUTHN-AUTHZ-SERVER/server
    ports:
      - 7070:80 # TODO: make external port a random number
      - 9230:9229 # this is the debug port
    restart: unless-stopped

volumes:
  server:

networks:
  default:
    external:
      name: skillup-network
